name: Hello World
author: Yair Elmaliah
description: Some Description
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: Yair

outputs:
  time:
    description: The greeting time

runs:
  using: 'node16'
  main: 'dist/index.js'
