on: push
jobs:
  testing-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: "Worls"
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"